site: KimDoubleB
title: KimDoubleB
greetings: KimDoubleB news 👋
description: >-
  Code never lies
lang: ko
timezone:  Asia/Seoul
repo: https://github.com/KimDoubleB/news
data-theme: light # default theme "dark" | "light"
discus-identifier: kimdoubleb-news

author:
  name: KimDoubleB
  bio: Code never lies
  userpicture: 
  username: KimDoubleB
  github: https://github.com/KimDoubleB
  twitter: # twitter username
  email: deadlock@kakao.com

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://kimdoubleb.github.io"
baseurl: "/news"
# local
# url: "http://localhost:4000" # 
# baseurl: "" # 
permalink: pretty



markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


